name: R-hello-world

on: [push]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - uses: r-lib/actions/setup-r@v1

      - name: Say hello
        run: |
          cat("Hello world! ğŸŒ")
        shell: Rscript {0}
